/*******************************************************************************
*                      Tableau contenant les nom et images                     *
*                                   Des films                                  *
*******************************************************************************/

let listeBlock = [
  ["venom", "Description du premier film", "./img/Film/Action/venom.jpg", "action"],
  ["21_Jump_Street", "Description du second film", "./img/Film/Action/21_Jump_Street.jpg", "action"],
  ["Equalizer", "Description du troisième film", "./img/Film/Action/Equalizer.jpg", "action"],
  ["Edge_of_Tomorrow", "Description du premier film", "./img/Film/Action/Edge_of_Tomorrow.jpg", "action"],
  ["American_History_X", "Description du second film", "./img/Film/Action/American_History_X.jpg", "action"],
  ["Fight_Club", "Description du troisième film", "./img/Film/Action/Fight_Club.jpg", "action"],
  ["Asterix_Le_Domaine_des_Dieux", "Description du premier film", "./img/Film/Animation/Asterix_Le_Domaine_des_Dieux.jpg", "animation"],
  ["Asterix_Obelix_Mission_Cleopatre", "Description du second film", "./img/Film/Animation/Asterix_Obelix_Mission_Cleopatre.jpg", "animation"],
  ["Blanche_Neige_et_les_Sept_Nains", "Description du troisième film", "./img/Film/Animation/Blanche_Neige_et_les_Sept_Nains.jpg", "animation"],
  ["Dragons", "Description du premier film", "./img/Film/Animation/Dragons.jpg", "animation"],
  ["L_Etrange_Noel_de_Monsieur_Jack", "Description du second film", "./img/Film/Animation/L_Etrange_Noel_de_Monsieur_Jack.jpg", "animation"],
  ["La_Belle_et_la_Bete", "Description du troisième film", "./img/Film/Animation/La_Belle_et_la_Bete.jpg", "animation"],
  ["moi_et_mechant", "Description du troisième film", "./img/Film/Animation/m&m.jpg", "animation"],
  ["Toy_Story", "Description du premier film", "./img/Film/Animation/Toy_Story.jpg", "animation"],
  ["Vice_Versa", "Description du second film", "./img/Film/Animation/Vice_Versa.jpg", "animation"],
  ["Wall_E", "Description du troisième film", "./img/Film/Animation/Wall_E.jpg", "animation"],
  ["Zootopia", "Description du premier film", "./img/Film/Animation/Zootopie.jpg", "animation"],
  ["Bienvenue_a_zombieland", "Description du troisième film", "./img/Film/Aventure/Bienvenue_a_Zombieland.jpg", "aventure"],
  ["28_Jours_Plus_Tard", "Description du troisième film", "./img/Film/Epouvante/28_Jours_Plus_Tard.jpg", "epouvante"],
  ["Alien_Le_Huitieme_Passager", "Description du troisième film", "./img/Film/Epouvante/Alien_Le_Huitieme_Passager.jpg", "epouvante"],
  ["American_Nightmare", "Description du premier film", "./img/Film/Epouvante/American_Nightmare.jpg", "epouvante"],
  ["Ca", "Description du second film", "./img/Film/Epouvante/Ca.jpg", "epouvante"],
  ["Conjuring_Les_Dossiers_Warren", "Description du troisième film", "./img/Film/Epouvante/Conjuring_Les_Dossiers_Warren.jpg", "epouvante"],
  ["Dernier_train_pour_Busan", "Description du premier film", "./img/Film/Epouvante/Dernier_train_pour_Busan.jpg", "epouvante"],
  ["Grave", "Description du second film", "./img/Film/Epouvante/Grave.jpg", "epouvante"],
  ["saw", "Description du troisième film", "./img/Film/Epouvante/saw.jpg", "epouvante"],
  ["Il_Faut_Sauver_le_Soldat_Ryan", "Description du premier film", "./img/Film/Historique/Il_Faut_Sauver_le_Soldat_Ryan.jpg", "historique"],
  ["la_vague", "Description du second film", "./img/Film/Historique/la_vague.jpg", "historique"],
  ["Une_merveilleuse_histoire_du_temps", "Description du troisième film", "./img/Film/Historique/Une_merveilleuse_histoire_du_temps.jpg", "historique"],
  ["Contact", "Description du premier film", "./img/Film/science-fiction/Contact.jpg", "science-fiction"],
  ["Deadpool", "Description du second film", "./img/Film/science-fiction/Deadpool.jpg", "science-fiction"],
  ["District_9", "Description du troisième film", "./img/Film/science-fiction/District_9.jpg", "science-fiction"],
  ["Donnie_Darko", "Description du troisième film", "./img/Film/Science-Fiction/Donnie_Darko.jpg", "science-fiction"],
  ["Gravity", "Description du premier film", "./img/Film/Science-Fiction/Gravity.jpg", "science-fiction"],
  ["Interstellar", "Description du second film", "./img/Film/Science-Fiction/Interstellar.jpg", "science-fiction"],
  ["tron", "Description du troisième film", "./img/Film/Science-Fiction/tron.jpg", "science-fiction"],
  ["the_punisher", "Description du premier film", "./img/Serie/the_punisher.jpg", "series_vf"],
  ["the_flash", "Description du second film", "./img/Serie/the_flash.jpg", "series_vf"],
  ["teen_wolf", "Description du troisième film", "./img/Serie/teen_wolf.jpg", "series_vf"],
  ["stargate", "Description du troisième film", "./img/Serie/stargate.jpg", "series_vf"],
  ["Dexter", "Description du premier film", "./img/Serie/Dexter.jpg", "series_vf"],
  ["dardevil", "Description du second film", "./img/Serie/dardevil.jpg", "series_vf"],
  ["breaking_bad", "Description du troisième film", "./img/Serie/breaking_bad.jpg", "series_vf"],
  ["boruto", "Description du troisième film", "./img/Manga/boruto.jpg", "manga"],
  ["dragon_ball_super", "Description du troisième film", "./img/Manga/dragon_ball_super.jpg", "manga"],
  ["naruto", "Description du premier film", "./img/Manga/naruto.jpg", "manga"],
  ["pokemon", "Description du second film", "./img/Manga/pokemon.jpg", "manga"],
  ["borutoo", "Description du troisième film", "./img/Manga/boruto.jpg", "manga_film"],
  ["dragon_ball_superr", "Description du troisième film", "./img/Manga/dragon_ball_super.jpg", "manga_film"],
  ["narutoo", "Description du premier film", "./img/Manga/naruto.jpg", "manga_film"],
  ["pokemonn", "Description du second film", "./img/Manga/pokemon.jpg", "manga_film"],
  ["your_name", "Description du troisième film", "./img/Manga/your_name.jpg", "manga_film"],
];
